Iter5: Adding enviroments variables support
Mr-Filatik/go-metrics-collector pull request #5
Opened 2024-12-02 13:28 UTC by Mr-Filatik

2024-12-04 12:56 UTC, s-shpak requested changes
1. Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.

2. Любые вопросы по комментариям можно и нужно задавать в общем канале пачки

3. Добавь в проект линтер `golangci-lint`. Здесь объясняется как это сделать: https://github.com/s-shpak/praktikum-golangci-lint . Также добавь его проверки в `Github Actions` и исправь все замечания, пожалуйста

4. Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-12-04 12:56 UTC, s-shpak commented on cmd/agent/config/config.go
> +	endpointEnv := os.Getenv("ADDRESS")
Вместо `Getenv` лучше использовать `LookupEnv` (https://pkg.go.dev/os#LookupEnv) для того чтобы отличать пустую переменную окружения от необъявленной

2024-12-04 12:56 UTC, s-shpak commented on cmd/agent/config/config.go
> +	flag.Parse()
Я бы поменял местами работу с переменными окружения и флагами: более читаемо было бы распарсить флаги в поля объекта конфигурации, а потом переписать их переменными окружения там, где это необходимо

2024-12-04 12:56 UTC, s-shpak commented on cmd/agent/main.go
> +		time.Sleep(time.Duration(pollInterval) * time.Second)
В стандартной библиотеке Go в пакете `time` есть структура `Tikcer` (https://pkg.go.dev/time#Ticker), которая очень хорошо подходит для решения этой задачи. Я советую тебе использовать ее или обертку над ней (https://pkg.go.dev/time#Tick) в связке с `select`-`case` для периодической отправки метрик с агента.

2024-12-04 12:56 UTC, s-shpak commented on cmd/agent/main.go
> +		//m.Log()
deadcode

2024-12-04 12:56 UTC, s-shpak commented on cmd/agent/main.go
> +		err := m.Foreach(func(metricType, metricName, metricValue string) error {
Не очень идиоматично: лучше итерируйся по всем метрикам в цикле и для каждой выполняй заданную функцию (более Go-style)

2024-12-04 12:56 UTC, s-shpak commented on cmd/agent/metric/metric.go
> +	if err := sendFunc("gauge", "Alloc", strconv.FormatFloat(metric.Alloc, 'f', -1, 64)); err != nil {
Кроме того лучше позволить отправителю самому решать, в каком виде он хочет получить значение для отправки: не стоит смешивать ответственности здесь

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/main.go
> +var stor storage.MemStorage
Не используй глобальные переменные. Ты можешь создавать объект, наполнять его и передавать туда, где он будет использоваться

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/main.go
> +	repo := repository.MemRepository{}
Используй здесь "конструктор"

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
1. Паниковать не надо: используй `log.Fatal` для:
    1. вывода ошибки
    2. завершения процесса с ошибкой

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/main.go
> +		http.Error(w, "Unexpected error.", http.StatusInternalServerError)
Нештатные ошибки необходимо логировать

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/main_test.go
> +		//{method: http.MethodPost, path: "/counter/testCounter/1", expectedCode: http.StatusOK, expectedBody: ""},
deadcode

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/repository/abstract/repository.go
> +type Repository interface {
В Go интерфейсы принято объявлять рядом с местом их использования: в одном пакете и, чаще всего, рядом с функцией/методом, которые их используют. Существуют исключения, но это не тот случай

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/repository/mem_repository.go
> +	for i, v := range r.datas {
Поэтому логичнее было бы хранить не слайс элементов, а мапу (или и то, и другое, но это кажется преждевременной оптимизацией)

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/storage/mem_storage.go
> +		return "0", errors.New("invalid metric type")
1. В go в случае ошибки первое возвращенное значение считается невалидным (за несколькими редкими исключениями из стандартной библиотеки), потому можно вернуть пустую строку
```suggestion
		return "", errors.New("invalid metric type")
```

2. В ошибки лучше добавлять контекст: например, текст, объясняющий, что именно пошло не так и где

2024-12-04 12:56 UTC, s-shpak commented on cmd/server/storage/mem_storage.go
> +	if err != nil {
Попробуй уменьшить вложенность кода, чтобы улучшить его читаемость

2024-12-04 13:51 UTC, Mr-Filatik commented on cmd/agent/main.go
> +		//m.Log()
Исправлено: удалено //m.Log()

2024-12-04 13:52 UTC, Mr-Filatik commented on cmd/server/main.go
> +	repo := repository.MemRepository{}
Исправлено: добавил конструкторы
repo := repository.New()
stor = storage.New(repo)

2024-12-04 14:36 UTC, Mr-Filatik commented on cmd/server/main.go
> +var stor storage.MemStorage
Исправлено
Добавил функции обёртки func UpdateMetricHandle(s abstract.Storage) http.HandlerFunc { }

2024-12-04 14:49 UTC, Mr-Filatik commented on cmd/agent/main.go
> +		time.Sleep(time.Duration(pollInterval) * time.Second)
Исправлено
Заменил на t := time.Tick(time.Duration(pollInterval) * time.Second)
Но пока не делал остановку (может и это не нужно)

2024-12-05 13:22 UTC, Mr-Filatik commented on cmd/server/main_test.go
> +		//{method: http.MethodPost, path: "/counter/testCounter/1", expectedCode: http.StatusOK, expectedBody: ""},
Исправлено
Пока удалил файл, добавлю тесты позже

2024-12-05 13:32 UTC, Mr-Filatik commented on cmd/server/storage/mem_storage.go
> +	if err != nil {
Исправлено
Разбил на методы

2024-12-05 14:23 UTC, Mr-Filatik commented on cmd/server/main.go
> +		http.Error(w, "Unexpected error.", http.StatusInternalServerError)
Исправлено
Добавил логирование

2024-12-06 09:29 UTC, Mr-Filatik commented on cmd/agent/main.go
> +		err := m.Foreach(func(metricType, metricName, metricValue string) error {
Исправлено, сделал итерацию по range всех метрик

2024-12-06 09:30 UTC, Mr-Filatik commented on cmd/server/repository/abstract/repository.go
> +type Repository interface {
Исправлено, перенёс в место где используется интерфейс

2024-12-06 09:31 UTC, Mr-Filatik commented on cmd/server/repository/mem_repository.go
> +	for i, v := range r.datas {
Не исправил, пока не нашёл времени разобраться со слайсами и мапами, хочу оставить пока так, чтобы сделать обдуманно

2024-12-06 09:32 UTC, Mr-Filatik commented on cmd/agent/metric/metric.go
> +	if err := sendFunc("gauge", "Alloc", strconv.FormatFloat(metric.Alloc, 'f', -1, 64)); err != nil {
Исправлено, добавил метод GetAll, который возвращает все метрики и для каждой выполняю отправку.

2024-12-06 11:02 UTC, Mr-Filatik commented on cmd/agent/config/config.go
> +	endpointEnv := os.Getenv("ADDRESS")
Исправлено: заменил Getenv на LookupEnv

2024-12-06 11:02 UTC, Mr-Filatik commented on cmd/agent/config/config.go
> +	flag.Parse()
Исправлено: сделал последовательно, более читаемо

2024-12-06 19:38 UTC, s-shpak commented on cmd/agent/config/config.go
> +	envEndpValue, isEndpValue := os.LookupEnv("ADDRESS")
Если функция в Go возвращает вторую переменную булевого типа, которая указывает на корректность выполнения операции и т.п., ее принято называть `ok`.

2024-12-06 19:38 UTC, s-shpak commented on cmd/agent/main.go
> +		time.Sleep(time.Duration(pollInterval) * time.Second)
Пока не нужно, ее можно будет добавить позже.

Этот комментарий можно зарезолвить

2024-12-06 19:42 UTC, s-shpak requested changes

2024-12-06 19:42 UTC, s-shpak commented on cmd/agent/main.go
> +			log.Printf("Response is done. StatusCode: %v.", resp.Status())
Если произошла ошибка, то объект `resp` может быть невалидным, и тогда к нему нельзя будет обращаться

2024-12-06 19:42 UTC, s-shpak commented on cmd/agent/main.go
Постарайся оставлять в `main.go` (и в пакете `main`) как можно меньше логики: там могут лежать только создание и настройка компонентов и запуск сервиса. Всю остальную логику нужно перенести в `internal`.

2024-12-06 19:42 UTC, s-shpak commented on cmd/agent/metric/metric.go
> +	metric.PollCount++
Сейчас это работает некорректно: счетчик увеличивается при каждом сборе метрика на 1, а сервер прибалвяет полученное значение к пердыдущему. Вот пример того, что может произойти:

- агент собрал метрики 3 раза и отправляет серверу это значение
- сервер сохраняет его
- агент собрал метрики еще 2 раза и отправляет серверу значение 5 (3 + 2)
- сервер прибавляет его к предыдущему. С т.з. сервера агент произвел 8 сборов метрик

Подумай, как это исправить

2024-12-07 10:23 UTC, Mr-Filatik commented on cmd/agent/metric/metric.go
> +	metric.PollCount++
В методе GetAll() пакета metric в agent при выводе значений происходит очистка счётчиков если указано соответствующее bool значение (сделал так на случай, если нужно просто что-то сделать с переменными, но не отправлять).
```
if isClearCounters {
	metric.PollCount = 0
}
```
Поэтому в данном случае, программа отрабатывает верно и на сервере будет 3 + 2 = 5.

2024-12-09 08:04 UTC, Mr-Filatik commented on cmd/agent/main.go
> +			log.Printf("Response is done. StatusCode: %v.", resp.Status())
Исправлено, добавил else

2024-12-09 08:04 UTC, Mr-Filatik commented on cmd/agent/config/config.go
> +	envEndpValue, isEndpValue := os.LookupEnv("ADDRESS")
Исправлено, назвал как ok и использовал shadowing

2024-12-09 08:11 UTC, Mr-Filatik commented on cmd/agent/main.go
Исправлено
Вынес всю логику с main.go

2024-12-09 08:12 UTC, Mr-Filatik commented on cmd/agent/metric/metric.go
> +	metric.PollCount++
По идее можно разбить на 2 метода, второй назвать ClearCounters, вызывать его после успешной отправки, но в работе ничего не поменяется

2024-12-09 12:50 UTC, s-shpak requested changes

2024-12-09 12:50 UTC, s-shpak commented on internal/agent/reporter/reporter.go
> +			} else {
Стилистическое, но важное: не используй `else`, когда нет необходимости: более плоский код проще читать. Здесь после строки 24 можно вызвать `return`.

2024-12-09 13:41 UTC, Mr-Filatik commented on internal/agent/reporter/reporter.go
> +			} else {
Исправлено
Поставил continue

2024-12-09 21:27 UTC, s-shpak approved these changes

2024-12-16 11:12 UTC, merged